# Form implementation generated from reading ui file '.\roady_gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from roady import Roady


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(576, 399)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Departure_city = QtWidgets.QLabel(parent=self.centralwidget)
        self.Departure_city.setGeometry(QtCore.QRect(30, 20, 111, 21))
        self.Departure_city.setObjectName("Departure_city")
        self.Departure_city_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Departure_city_input.setGeometry(QtCore.QRect(130, 20, 113, 21))
        self.Departure_city_input.setObjectName("Departure_city_input")
        self.Destination_city = QtWidgets.QLabel(parent=self.centralwidget)
        self.Destination_city.setGeometry(QtCore.QRect(320, 20, 121, 21))
        self.Destination_city.setObjectName("Destination_city")
        self.Destination_city_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Destination_city_input.setGeometry(QtCore.QRect(410, 20, 113, 21))
        self.Destination_city_input.setObjectName("Destination_city_input")
        self.fuel_type = QtWidgets.QComboBox(parent=self.centralwidget)
        self.fuel_type.setGeometry(QtCore.QRect(30, 70, 68, 22))
        self.fuel_type.setObjectName("fuel_type")
        self.fuel_type.addItem("")
        self.fuel_type.addItem("")
        self.fuel_usage = QtWidgets.QLabel(parent=self.centralwidget)
        self.fuel_usage.setGeometry(QtCore.QRect(30, 120, 49, 16))
        self.fuel_usage.setObjectName("fuel_usage")
        self.fuel_uasge_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.fuel_uasge_input.setGeometry(QtCore.QRect(100, 110, 113, 21))
        self.fuel_uasge_input.setObjectName("fuel_uasge_input")
        self.persons = QtWidgets.QLabel(parent=self.centralwidget)
        self.persons.setGeometry(QtCore.QRect(30, 160, 49, 16))
        self.persons.setObjectName("persons")
        self.persons_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.persons_input.setGeometry(QtCore.QRect(90, 160, 113, 21))
        self.persons_input.setObjectName("persons_input")
        self.calculate_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculate_button.clicked.connect(self.calculate_btn)
        self.calculate_button.setGeometry(QtCore.QRect(240, 220, 111, 31))
        self.calculate_button.setObjectName("calculate_button")
        self.add_return_radio_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.add_return_radio_button.setGeometry(QtCore.QRect(220, 70, 89, 20))
        self.add_return_radio_button.setObjectName("add_return_radio_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 576, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Departure_city.setText(_translate("MainWindow", "Departure City"))
        self.Destination_city.setText(_translate("MainWindow", "Desination City"))
        self.fuel_type.setItemText(0, _translate("MainWindow", "Benzina"))
        self.fuel_type.setItemText(1, _translate("MainWindow", "Motorina"))
        self.fuel_usage.setText(_translate("MainWindow", "Consum"))
        self.persons.setText(_translate("MainWindow", "Persons"))
        self.calculate_button.setText(_translate("MainWindow", "Calculate"))
        self.add_return_radio_button.setText(_translate("MainWindow", "Dus/Intors"))

    def calculate_btn(self):
        departure_city = self.Departure_city_input.text()
        destination_city = self.Destination_city_input.text()
        number_of_persons = self.persons_input.text()
        fuel_type = self.fuel_type.currentText()
        fuel_usage = self.fuel_uasge_input.text()

        roady = Roady(departure_city, destination_city,
                      int(number_of_persons), float(fuel_usage), fuel_type)

        print(roady.calculate_price_per_person())


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
